# Generated by Django 3.1.7 on 2021-03-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discription',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
